export const ImageObj = {
    SunLogo: { Key: 'SunLogo', Path: 'assets\\Logo.png' },
    GameLogo: { Key: 'GameLogo', Path: 'assets\\sprites\\Logo.png' },
    Background: { Key: 'Background', Path: 'assets\\sprites\\BackdropMain.png' },
    Bullet: { Key: 'Bullet', Path: 'assets\\sprites\\Bullet.png' },
    BulletCollision: { Key: 'BulletCollision', Path: 'assets\\sprites\\BulletCollision.png' },
    ButtonBack: { Key: 'ButtonBack', Path: 'assets\\sprites\\ButtonBack.png' },
    ButtonBuy: { Key: 'ButtonBuy', Path: 'assets\\sprites\\ButtonBuy.png' },
    ButtonCreadits: { Key: 'ButtonCreadits', Path: 'assets\\sprites\\ButtonCredits.png' },
    ButtonMusicOff: { Key: 'ButtonMusicOff', Path: 'assets\\sprites\\ButtonMusicOff.png' },
    ButtonMusicOn: { Key: 'ButtonMusicOn', Path: 'assets\\sprites\\ButtonMusicOn.png' },
    ButtonPlayAgain: { Key: 'ButtonPlayAgain', Path: 'assets\\ButtonPlayAgain.png' },
    ButtonPlayGame: { Key: 'ButtonPlayGame', Path: 'assets\\sprites\\ButtonPlayGame.png' },
    ButtonQuit: { Key: 'ButtonQuit', Path: 'assets\\sprites\\ButtonQuit.png' },
    ButtonSelect: { Key: 'ButtonSelect', Path: 'assets\\sprites\\ButtonSelect.png' },
    ButtonShop: { Key: 'ButtonShop', Path: 'assets\\sprites\\ButtonShop.png' },
    ButtonShopDeadScreen: {
        Key: 'ButtonShopDeadScreen',
        Path: 'assets\\sprites\\ButtonShopDeathScreen.png',
    },
    ButtonSoundOff: { Key: 'ButtonSoundOff', Path: 'assets\\sprites\\ButtonSoundOff.png' },
    ButtonSoundOn: { Key: 'ButtonSoundOn', Path: 'assets\\sprites\\ButtonSoundOn.png' },
    Coin: { Key: 'Coin', Path: 'assets\\sprites\\Coin.png' },
    FlyFire: { Key: 'FlyFire', Path: 'assets\\sprites\\FlyFire.png' },
    FlyFire2: { Key: 'FlyFire2', Path: 'assets\\sprites\\FlyFire2.png' },
    icon: { Key: 'icon', Path: 'assets\\sprites\\icon.png' },
    logoGlow: { Key: 'logoGlow', Path: 'assets\\sprites\\logoGlow.png' },
    LogoSmall: { Key: 'LogoSmall', Path: 'assets\\sprites\\LogoSmall.png' },
    Menu: { Key: 'Menu', Path: 'assets\\sprites\\Menu.png' },
    PlayerDead: { Key: 'PlayerDead', Path: 'assets\\sprites\\PlayerDead.png' },
    PlayerFly: { Key: 'PlayerFly', Path: 'assets\\sprites\\PlayerFly.png' },
    Rocket: { Key: 'Rocket', Path: 'assets\\sprites\\Rocket.png' },
    RocketWarning: { Key: 'RocketWarning', Path: 'assets\\sprites\\RocketWarning.png' },
    SoundOff: { Key: 'SoundOff', Path: 'assets\\sprites\\SoundOff.png' },
    SoundOn: { Key: 'SoundOn', Path: 'assets\\sprites\\SoundOn.png' },
    SplashArt: { Key: 'SplashArt', Path: 'assets\\sprites\\SplashArt.png' },
    Zapper1: { Key: 'Zapper1', Path: 'assets\\sprites\\Zapper1.png' },
    Zapper2: { Key: 'Zapper2', Path: 'assets\\sprites\\Zapper2.png' },
    Zapper3: { Key: 'Zapper3', Path: 'assets\\sprites\\Zapper3.png' },
    Zapper4: { Key: 'Zapper4', Path: 'assets\\sprites\\Zapper4.png' },
    Ground: { Key: 'Ground', Path: 'assets\\sprites\\platform.png' },

    playerGreen: { key: 'playerGreen', path: 'assets\\sprites\\skins\\PlayerFly_Green.png' },
    playerOrange: { key: 'playerOrange', path: 'assets\\sprites\\skins\\PlayerFly_Orange.png' },
    playerPerry: { key: 'playerPerry', path: 'assets\\sprites\\skins\\PlayerFly_Perry.png' },
    playerPink: { key: 'playerPink', path: 'assets\\sprites\\skins\\PlayerFly_Pink.png' },
    playerRed: { key: 'playerRed', path: 'assets\\sprites\\skins\\PlayerFly_Red.png' },
    playerYellow: { key: 'playerYellow', path: 'assets\\sprites\\skins\\PlayerFly_Yellow.png' },
}
